// Design tokens (the document's variables) as code — CSS custom properties per theme, a Tailwind
// config, W3C design-token JSON, or a React Native module — and a diff against a code file.
import { deltaE, parseColor, toHex } from "../verify/color.js";

const UNITLESS = /weight|opacity|ratio|line-?height|z-?index|scale|flex|order/i;
const kebab = (s) =>
  String(s)
    .replace(/^\$/, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^\w-]+/g, "-")
    .replace(/_/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
const camel = (s) => kebab(s).replace(/-(\w)/g, (_, c) => c.toUpperCase());

/**
 * Normalizes variables into { name, type, values: { [theme|"default"]: value } } and the theme
 * axis ({ mode: ["light", "dark"] } -> axis "mode", themes ["light", "dark"]).
 */
export function normalizeTokens(variables = {}, themes = {}) {
  const [axis, list] = Object.entries(themes)[0] ?? [null, []];
  const tokens = [];
  for (const [name, v] of Object.entries(variables)) {
    const values = {};
    if (Array.isArray(v.value)) {
      for (const e of v.value) {
        const t = e.theme ? Object.values(e.theme)[0] : "default";
        values[t] = e.value;
      }
    } else values.default = v.value;
    tokens.push({ name, type: v.type, values });
  }
  return { axis, themes: list ?? [], tokens };
}

const cssValue = (t, v) => {
  if (t.type === "number") return UNITLESS.test(t.name) ? String(v) : `${v}px`;
  if (t.type === "string" && /\s/.test(v) && !/^["']/.test(v)) return `"${v}"`;
  return String(v);
};
const baseTheme = (n) => (n.themes.includes("light") ? "light" : n.themes[0]);
/** The value for the base selector: the default, else the first (usually light) theme's. */
const baseValue = (n, t) => t.values.default ?? t.values[baseTheme(n)] ?? Object.values(t.values)[0];

export function renderTokens(n, format) {
  const base = baseTheme(n);
  if (format === "css") {
    const lines = ["/* Generated by pen-multi from the design's variables. Edit the design, then regenerate. */", ":root {"];
    for (const t of n.tokens) lines.push(`  --${kebab(t.name)}: ${cssValue(t, baseValue(n, t))};`);
    lines.push("}");
    for (const theme of n.themes) {
      if (theme === base) continue;
      const own = n.tokens.filter((t) => t.values[theme] !== undefined && t.values[theme] !== baseValue(n, t));
      if (!own.length) continue;
      lines.push("", `[data-${kebab(n.axis ?? "theme")}="${theme}"]${/dark|night|toi|tối/i.test(theme) ? ", .dark" : ""} {`);
      for (const t of own) lines.push(`  --${kebab(t.name)}: ${cssValue(t, t.values[theme])};`);
      lines.push("}");
      if (/dark|night|toi|tối/i.test(theme)) {
        lines.push("", "@media (prefers-color-scheme: dark) {", `  :root:not([data-${kebab(n.axis ?? "theme")}]) {`);
        for (const t of own) lines.push(`    --${kebab(t.name)}: ${cssValue(t, t.values[theme])};`);
        lines.push("  }", "}");
      }
    }
    return `${lines.join("\n")}\n`;
  }
  if (format === "tailwind") {
    const group = (t) => {
      if (t.type === "color") return "colors";
      if (t.type !== "number") return null;
      if (/radius|round/i.test(t.name)) return "borderRadius";
      if (/font|text|size|type/i.test(t.name) && !/weight/i.test(t.name)) return "fontSize";
      if (/weight/i.test(t.name)) return "fontWeight";
      return "spacing";
    };
    const theme = {};
    for (const t of n.tokens) {
      const g = group(t);
      if (!g) continue;
      (theme[g] ??= {})[kebab(t.name)] = `var(--${kebab(t.name)})`;
    }
    return `// Generated by pen-multi. Values live in the CSS variables (tokens --format css); themes switch them.\n/** @type {import('tailwindcss').Config['theme']} */\nmodule.exports = { extend: ${JSON.stringify(theme, null, 2)} };\n`;
  }
  if (format === "json") {
    // W3C Design Tokens Community Group format, one group per theme.
    const type = (t) => (t.type === "color" ? "color" : t.type === "number" ? (UNITLESS.test(t.name) ? "number" : "dimension") : "string");
    const value = (t, v) => (t.type === "number" && !UNITLESS.test(t.name) ? `${v}px` : v);
    const out = {};
    const themes = n.themes.length ? n.themes : ["default"];
    for (const theme of themes) {
      const g = (out[theme] = {});
      for (const t of n.tokens) {
        const v = t.values[theme] ?? t.values.default ?? baseValue(n, t);
        g[kebab(t.name)] = { $type: type(t), $value: value(t, v) };
      }
    }
    return `${JSON.stringify(out, null, 2)}\n`;
  }
  if (format === "react-native") {
    const themes = n.themes.length ? n.themes : ["default"];
    const body = themes.map((theme) => {
      const entries = n.tokens.map((t) => `    ${camel(t.name)}: ${JSON.stringify(t.values[theme] ?? t.values.default ?? baseValue(n, t))},`);
      return `  ${JSON.stringify(theme)}: {\n${entries.join("\n")}\n  },`;
    });
    return `// Generated by pen-multi from the design's variables. Edit the design, then regenerate.\nexport const tokens = {\n${body.join("\n")}\n} as const;\nexport type ThemeName = keyof typeof tokens;\n`;
  }
  throw new Error(`Unknown token format ${format}; use css, tailwind, json or react-native.`);
}

/** Token values found in a code file: CSS custom properties (per selector theme) or token JSON. */
export function readCodeTokens(text, n) {
  const found = new Map(); // `${theme}|${kebab}` -> value
  const themeOf = (selector) => {
    const m = n.themes.find((t) => t !== baseTheme(n) && new RegExp(`\\b${t}\\b`, "i").test(selector));
    return m ?? (/\bdark\b/i.test(selector) ? n.themes.find((t) => /dark|night|toi|tối/i.test(t)) ?? "dark" : baseTheme(n) ?? "default");
  };
  if (/^\s*[{[]/.test(text)) {
    const json = JSON.parse(text);
    const walk = (o, theme, prefix) => {
      for (const [k, v] of Object.entries(o)) {
        if (v && typeof v === "object" && "$value" in v) found.set(`${theme}|${kebab(prefix ? `${prefix}-${k}` : k)}`, v.$value);
        else if (v && typeof v === "object") walk(v, n.themes.includes(k) ? k : theme, n.themes.includes(k) ? prefix : prefix ? `${prefix}-${k}` : k);
        else found.set(`${theme}|${kebab(prefix ? `${prefix}-${k}` : k)}`, v);
      }
    };
    walk(json, baseTheme(n) ?? "default", "");
    return found;
  }
  const block = /([^{}]+)\{([^{}]*)\}/g;
  for (let m; (m = block.exec(text)); ) {
    const theme = themeOf(m[1]);
    for (const d of m[2].matchAll(/--([\w-]+)\s*:\s*([^;}]+);?/g)) found.set(`${theme}|${d[1].toLowerCase()}`, d[2].trim());
  }
  return found;
}

const sameValue = (t, design, code) => {
  if (t.type === "color") {
    const a = parseColor(design), b = parseColor(code);
    return a && b ? deltaE(a, b) < 1 : String(design).toLowerCase() === String(code).toLowerCase();
  }
  if (t.type === "number") return Math.abs(Number(design) - parseFloat(code)) < 0.01;
  return String(design).replace(/^["']|["']$/g, "") === String(code).replace(/^["']|["']$/g, "");
};

/** Differences between the design's tokens and a code file's: missing, changed, and extra names. */
export function diffTokens(n, codeText) {
  const code = readCodeTokens(codeText, n);
  const missing = [], changed = [];
  const themes = n.themes.length ? n.themes : ["default"];
  const known = new Set();
  for (const t of n.tokens) {
    const key = kebab(t.name);
    // A token with one value is compared once; a themed one per theme.
    const themed = Object.keys(t.values).some((k) => k !== "default");
    for (const theme of themed ? themes : [baseTheme(n) ?? "default"]) {
      const want = t.values[theme] ?? t.values.default ?? baseValue(n, t);
      const at = code.get(`${theme}|${key}`) ?? (theme === baseTheme(n) ? code.get(`default|${key}`) : code.get(`${baseTheme(n)}|${key}`));
      known.add(key);
      if (at === undefined) {
        if (theme === baseTheme(n) || !themed || t.values[theme] !== undefined) missing.push({ name: key, theme: themed ? theme : "default", design: want });
        continue;
      }
      if (!sameValue(t, want, at)) changed.push({ name: key, theme: themed ? theme : "default", design: t.type === "color" ? toHex(parseColor(want)) ?? want : want, code: at });
    }
  }
  const extra = [...new Set([...code.keys()].map((k) => k.split("|")[1]))].filter((k) => !known.has(k));
  return { missing, changed, extra };
}
